---
- hosts: aws_ec2
  become: yes
  connection: ssh
  remote_user: ec2-user   # or use ansible_ssh_user

  vars:
    ansible_ssh_private_key_file: "/path/to/karthikmumbai1.pem"
    ansible_ssh_user: "ec2-user"

  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present

    - name: restart httpd
      service:
        name: httpd
        state: restarted

    - name: install git in dev server
      yum:
        name: git
        state: present

    - name: get the source code from github
      git:
        repo: "https://github.com/devops0014/staticsite-docker.git"
        dest: /var/www/
        update: yes
        version: master
